### ISSUE TITLE
Not an issue But want to understand (I am new to foundry)

### ISSUE THREAD

**Issue by BilalXulfiqar** [SunWeb3Sec/DeFiVulnLabs#49]
In Reentrancy.sol
we have contracts EtherStore and EtherStoreRemediated but in tests we have 4 contracts additional two attack and attackRemediated  
I cant locate  2 additional contracts . Is there any trick to it. Am I missing something ???

**Comment by SunWeb3Sec** [comment]
You can just execute:
forge test --contracts src/test/Reentrancy.sol -vv
