### ISSUE TITLE
Dirtybytes test failed

### ISSUE THREAD

**Issue by LinLL** [SunWeb3Sec/DeFiVulnLabs#8]
Dirtybytes need to complile under 0.8.15.

**Comment by SunWeb3Sec** [comment]
Thanks for the report, I will check it later

**Comment by SunWeb3Sec** [comment]
Fixed https://github.com/SunWeb3Sec/DeFiVulnLabs/commit/02cd54f1848228b29fc31e2452e8d62da97b502b
